### ISSUE TITLE
Unexpected warning message

### ISSUE THREAD

**Issue by KaiChuan-Hsieh** [intel/ipu6-camera-hal#14]
四  19 19:11:08 TRBA-DVT2-C3 sh[925]: [04-19 19:10:00.990] CamHAL[INF] aiqb file name ov01a10.aiqb
 四  19 19:11:08 TRBA-DVT2-C3 sh[925]: [04-19 19:10:00.991] CamHAL[INF] aiqb file name ov01a10.aiqb
 四  19 19:11:08 TRBA-DVT2-C3 sh[925]: [04-19 19:10:09.835] CamHAL[WAR] ipu6_bb_video_bayer: wait executors timeout
 四  19 19:11:08 TRBA-DVT2-C3 sh[925]: [04-19 19:10:09.968] CamHAL[WAR] ipu6_bb_video_bayer: wait executors timeout
 四  19 19:11:08 TRBA-DVT2-C3 sh[925]: [04-19 19:10:12.638] CamHAL[WAR] ipu6_bb_video_bayer: wait executors timeout
 四  19 19:11:08 TRBA-DVT2-C3 sh[925]: [04-19 19:10:24.250] CamHAL[WAR] ipu6_bb_video_bayer: wait executors timeout
 四  19 19:11:08 TRBA-DVT2-C3 sh[925]: [04-19 19:10:27.320] CamHAL[WAR] ipu6_bb_video_bayer: wait executors timeout
[ipu6_bb_video_bayer.log](https://github.com/intel/ipu6-camera-hal/files/8527057/ipu6_bb_video_bayer.log)

The full log is

**Comment by ccgjimlai** [comment]
It is not an error. Only a runtime warning.
It means psys executor wait input timeout. Sometimes it indicates one frame was lost. In our validation cycle, we didn’t find that occur continually. 
Could you confirm that you have applied “buffer-count=7” parameter on icamerasrc?

**Comment by KaiChuan-Hsieh** [comment]
After adding buffer-count=7 parameter, the issue was gone. Thanks for your suggestion.
